[package]
name = "gotchao_core"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
needletail = "0.5"
rayon = "1.8"
csv = "1.3"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }